data:
  image: tianon/true
  volumes:
    - ./container-files/etc/nginx:/etc/nginx
    - ./container-files/var/cache/nginx:/var/cache/nginx
    - ./container-files/var/www:/var/www
    - ./container-files/etc/php5/cli/php.ini:/etc/php5/cli/php.ini
    - ./container-files/etc/php5/fpm/php.ini:/etc/php5/fpm/php.ini
    - ./container-files/etc/php5/fpm/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./container-files/etc/php5/fpm/pool.d/www.conf:/etc/php5/fpm/pool.d/www.conf
    - ./container-files/var/lib/php5/sessions:/var/lib/php5/sessions
    - ./container-files/etc/mysql/my.cnf:/etc/mysql/my.cnf
    - ./container-files/var/lib/mysql:/var/lib/mysql

nginx:
  image: yfix/nginx
  restart: always
  ports:
    - "30180:80"
  links:
    - php
    - memcached
  volumes_from:
    - data

php:
  image: yfix/php
  restart: always
  ports:
    - "39001:9000"
  links:
    - mysql
    - memcached
    - redis
    - rabbitmq
  volumes_from:
    - data

mysql:
  image: yfix/mysql
  restart: always
  ports:
    - "33061:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=yf_for_unit_tests
    - MYSQL_USER=yf_test
    - MYSQL_PASSWORD=yf_test
  volumes_from:
    - data

ssh:
  image: yfix/ssh
  restart: always
  privileged: true
  ports:
    - "30221:22"
  links:
    - nginx
    - php
    - mysql
  volumes_from:
    - data

memcached:
  image: memcached
  restart: always
  ports:
    - "31111:11211"
  command: memcached -m 8

redis:
  image: redis
  restart: always
  ports:
    - "36379:6379"

rabbitmq:
  image: rabbitmq
  restart: always
  hostname: yfix-rabbitmq
  ports:
    - "34369:4369"
    - "35671:5671"
    - "35672:5672"
    - "35673:25672"

#sphinxsearch:
#  image: yfix/sphinxsearch
#  restart: always
#  ports:
#    - "39301:9306"
