data:
  image: tianon/true
  volumes:
    - ./container-files/var/www:/var/www
    - ./container-files/var/log/supervisor:/var/log/supervisor

nginx:
  image: yfix/nginx
  restart: always
  ports:
    - "30180:80"
  links:
    - php
    - memcached
  volumes_from:
    - data
  volumes:
    - ./container-files/etc/nginx:/etc/nginx
    - ./container-files/var/cache/nginx:/var/cache/nginx
    - ./container-files/var/log/nginx:/var/log/nginx
    - ./container-files/etc/supervisor/conf.d/nginx.conf:/etc/supervisor/conf.d/nginx.conf

php:
  image: yfix/php
  restart: always
  links:
    - mysql
    - memcached
  volumes_from:
    - data
  volumes:
    - ./container-files/etc/php5/cli/php.ini:/etc/php5/cli/php.ini
    - ./container-files/etc/php5/fpm/php.ini:/etc/php5/fpm/php.ini
    - ./container-files/etc/php5/fpm/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./container-files/etc/php5/fpm/pool.d/www.conf:/etc/php5/fpm/pool.d/www.conf
    - ./container-files/var/log/php5:/var/log/php5
    - ./container-files/var/lib/php5/sessions:/var/lib/php5/sessions
    - ./container-files/etc/supervisor/conf.d/php5-fpm.conf:/etc/supervisor/conf.d/php5-fpm.conf

mysql:
  image: yfix/mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=yf_for_unit_tests
    - MYSQL_USER=yf_test
    - MYSQL_PASSWORD=yf_test
  volumes_from:
    - data
  volumes:
    - ./container-files/etc/mysql/my.cnf:/etc/mysql/my.cnf
    - ./container-files/var/lib/mysql:/var/lib/mysql

ssh:
  image: yfix/ssh
  restart: always
  privileged: true
  ports:
    - "30221:22"
  volumes_from:
    - data
  volumes:
    - ./container-files/config/authorized_keys:/config/authorized_keys:ro
    - ./container-files/etc/supervisor/conf.d/sshd.conf:/etc/supervisor/conf.d/sshd.conf

memcached:
  image: memcached
  restart: always
  command: memcached -m 8
